const teamLists = [
  {
    fName: "Doug",
    lName: "Dixon",
    imgLink: "db/images/people/ddixon.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "M.A.Sc.",
    title: "President",
    group: "Leadership",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Jigish",
    lName: "Naik",
    imgLink: "db/images/people/jnaik.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "M.Sc.",
    title: "Partner",
    group: "Leadership",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Chris",
    lName: "Middleton",
    imgLink: "db/images/people/cmiddleton.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Senior Project Manager",
    group: "Professionals",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Lolo",
    lName: "Tsung",
    imgLink: "db/images/people/ltsung.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Senior Project Manager",
    group: "Professionals",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Charlotte",
    lName: "Bond",
    imgLink: "db/images/people/cbond.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Senior Bridge Engineer",
    group: "Professionals",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Jamie",
    lName: "Yeung",
    imgLink: "db/images/people/jyeung.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "PhD.",
    title: "Project Engineer",
    group: "Professionals",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Sach",
    lName: "Jayasuriya",
    imgLink: "db/images/people/sjayasuriya.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Bridge Engineer",
    group: "Professionals",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Kevin",
    lName: "Li",
    imgLink: "db/images/people/kli.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Bridge Engineer",
    group: "Professionals",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Hayley",
    lName: "Kokkinakis",
    imgLink: "db/images/people/hkokkinakis.jpeg",
    refLink: "#team",
    suffix: "EIT",
    altSuffix: "",
    title: "Bridge Designer",
    group: "Designers",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Adam",
    lName: "Aubin",
    imgLink: "db/images/people/aaubin.jpeg",
    refLink: "#team",
    suffix: "EIT",
    altSuffix: "",
    title: "Bridge Designer",
    group: "Designers",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Mahdi",
    lName: "Alfakisamani",
    imgLink: "db/images/people/unknown.jpg",
    refLink: "#team",
    suffix: "",
    altSuffix: "PhD.",
    title: "Junior Bridge Designer",
    group: "Designers",
    content: ["paragraph 1", "paragraph 2"],
  },
  {
    fName: "Evan",
    lName: "Tije",
    imgLink: "db/images/people/unknown.jpg",
    refLink: "#team",
    suffix: "",
    altSuffix: "",
    title: "Junior Bridge Designer",
    group: "Designers",
    content: ["paragraph 1", "paragraph 2"],
  },
];

export default teamLists;
