const careersList = [
  {
    title: "CAD Technician",
    category: "Technician",
    type: "Full Time",
    location: "Brampton, Ontario",
    description:
      "This position will be attractive to those wishing to develop their knowledge in CAD procedures and Bridge Information Modeling (BIM) in a design office that can provide various opportunities and challenges. The candidate will prepare preliminary and detailed design drawings for various bridges, culverts, retaining walls and other transportation-related structures. The Candidate should have experience in preparing bridge drawings. Leadership in developing standards and supervising junior staff should also be expected. Additional responsibilities include:",
    descriptionList: [
      "Collaborate with Bridge Engineers in the development of Contract Drawings in AutoCAD (2D and 3D) and BIM",
      "Review drawings prepared by more junior staff to ensure quality and compliance with standards",
      "Maintain current in ongoing developments in CAD",
    ],
    qualification: "",
    qualificationList: [
      "College diploma or equivalent experience",
      "Previous experience in a Bridge Consulting environment",
      "Proficient in the use of AutoCAD software",
      "Knowledge of BrIM, Revit, and MicroStation is preferred but not necessary",
      "Knowledge of other software, such as SketchUp, is considered an asset",
      "Excellent verbal and written skills",
      "Previous experience working in a Team environment in a consulting office is desirable",
    ],
  },
  {
    title: "Senior Bridge Engineer",
    category: "Professional",
    type: "Full Time",
    location: "Brampton, Ontario",
    description:
      "This position will be attractive to an established Bridge Engineer who already possesses progressive experience in all aspects of the design and construction of bridges, retaining walls and other transportation related structures. The Candidate should have experience in leading multi-discipline design teams to prepare new and rehabilitation bridge designs. In this position, you will also be expected to undertake various corporate management tasks, manage and develop client relationships, pursue new business growth opportunities and mentor junior staff. Additional responsibilities include:",
    descriptionList: [
      "Management of all aspects of projects including staff utilization, and budgets",
      "Technical responsibility for project team",
      "Preparation of Contract Documents for a variety of projects involving transportation structures",
      "Construction liaison for Projects during construction",
      "Other responsibilities as may be assigned",
    ],
    qualification: "",
    qualificationList: [
      "Undergraduate or graduate degree in Civil / Structural Engineering from an accredited university",
      "Licenced Professional Engineer with Professional Engineers Ontario (or other Provincial / Territorial Association)",
      "Minimum of twelve (12) years of design experience for new and rehabilitation Bridge Design for a variety of bridge types and materials",
      "Experience with Ministry of Transportation – Ontario standards, procedures and practices as well as those of other GTA Municipalities",
      "Knowledgeable in the use of analysis software including CSI-Bridge and SAP2000 for the evaluation and analysis of all types of bridges",
      "Excellent verbal and written communication skills including proven ability to prepare high quality reports and proposals",
      "Knowledge of the Canadian Highway Bridge Design Code gained through use in detailed bridge designs including foundation design / evaluation",
      "Ability to work independently, provide direction to a Project Team and proven ability to manage projects",
      "Preference given to those experienced in the design, evaluation and rehabilitation of light rapid transit and heavy haul (Class 1) rail carrying bridges",
    ],
  },
  {
    title: "Bridge Engineer",
    category: "Professional",
    type: "Full Time",
    location: "Brampton, Ontario",
    description:
      "This position will be attractive to those wishing to further advance their Bridge Engineer career in a design office that can provide the required opportunities and guidance. Candidate will undertake the preliminary and detailed design of a variety of bridges, culverts, retaining walls and other transportation related structures. The Candidate should have experience in undertaking bridge inspections, investigations and report preparation. The candidate should be able to undertake management tasks, pursue new business growth opportunities, direct CAD technicians and mentor junior staff. Additional responsibilities include:",
    descriptionList: [
      "Preparation of Contract Documents for a variety of transportation related projects involving transportation structures (using OPSS and MTO Specifications)",
      "Prepare preliminary and detailed designs under the supervision of a Senior Bridge Engineer and review progress CAD drawings",
      "Construction liaison for Projects during construction",
      "Other responsibilities as may be assigned",
    ],
    qualification: "",
    qualificationList: [
      "Undergraduate or graduate degree in Civil / Structural Engineering from an accredited university;",
      "Licences Professional Engineer with Professional Engineers Ontario (or other Provincial / Territorial Association) for at least four (4) years",
      "Six to twelve (6-12) years of design experience for new and rehabilitation Bridge Design for a variety of bridge types and materials",
      "Experience with Ministry of Transportation – Ontario standards, procedures and practices as well as those of other GTA Municipalities",
      "Knowledgeable in the use of analysis software including CSI-Bridge and SAP2000 for the evaluation and analysis of all types of bridges and working knowledge of AUTO CAD",
      "Excellent verbal and written communication skills including proven ability to prepare high quality reports and proposals",
      "Knowledge of the Canadian Highway Bridge Design Code gained through use in detailed bridge designs",
      "Ability to work independently as well as provide direction to other members of a Project Team",
      "Experienced in bridge rehabilitation techniques and methodologies currently used in the local market",
    ],
  },
  // {
  //   title: "Bridge Designer - Coop",
  //   category: "Designer",
  //   type: "Internship",
  //   location: "Brampton, Ontario",
  //   description: "",
  //   descriptionList: ["Loading..."],
  //   qualification: "",
  //   qualificationList: ["Loading..."],
  // },
];

export default careersList;
