const projectLists = [
  {
    img: "db/images/projects/eastern-ave-fatigue-evaluation.jpg",
    refLink: "#projects",
    projectTitle: "Eastern Avenue Interchange Fatigue Evaluation",
    city: "Toronto",
    province: "Ontario",
    client: "City of Toronto",
    projectType: "evaluation",
  },
  {
    img: "db/images/projects/ship-channel-rehabilitation.jpg",
    refLink: "#projects",
    projectTitle: "Cherry Street Bascule Bridge Rehabilitation - Phase I",
    city: "Toronto",
    province: "Ontario",
    client: "Ports Toronto",
    projectType: "specialty",
  },
  {
    img: "db/images/projects/dvp-coating-rehabilitation.jpg",
    refLink: "#projects",
    projectTitle: "Don Valley Parkway Steel Bridges Coating Rehabilitation",
    city: "Toronto",
    province: "Ontario",
    client: "City of Toronto",
    projectType: "design",
  },
  {
    img: "db/images/projects/third-street-bridge-replacement.jpg",
    refLink: "#projects",
    projectTitle: "Third Street Bridge Rehabilitation",
    city: "Chatham-Kent",
    province: "Ontario",
    client: "Municipality of Chatham-Kent",
    projectType: "design",
  },
  {
    img: "db/images/projects/various-culvert-rehabilitation.jpg",
    refLink: "#projects",
    projectTitle: "City of Toronto Culverts Rehabilitation and Replacement",
    city: "Toronto",
    province: "Ontario",
    client: "City of Toronto",
    projectType: "design",
  },
  {
    img: "db/images/projects/osim-inspection.jpg",
    refLink: "#projects",
    projectTitle: "City of Toronto Biennial OSIM Inspection Program",
    city: "Toronto",
    province: "Ontario",
    client: "City of Toronto",
    projectType: "inspection",
  },
  {
    img: "db/images/projects/fgge-hammer-sounding.jpg",
    refLink: "#projects",
    projectTitle: "Gardiner Expressway Soffit and Substructure Delamination Inspection",
    city: "Toronto",
    province: "Ontario",
    client: "City of Toronto",
    projectType: "inspection",
  },
  {
    img: "db/images/projects/nwr-underwater-inspection.jpg",
    refLink: "#projects",
    projectTitle: "MTO Northwest Region Bridges and Culverts Underwater Inspection",
    city: "",
    province: "North-Western Ontario",
    client: "MTO Northwest Region",
    projectType: "inspection",
  },
];

export default projectLists;
