const teamLists = [
  {
    fName: "Doug",
    lName: "Dixon",
    imgLink: "db/images/people/ddixon.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "M.A.Sc.",
    title: "President",
    group: "Leadership",
    content: [
      "Doug is the President and a Senior Bridge Engineer at Doug Dixon & Associates Inc. (DDA). Doug has more than 40 years of bridge engineering and project management experience. Doug has been a Registered Professional Engineer in the Province of Ontario since 1984. Prior to opening DDA, Doug spent more than 28 years with McCormick Rankin Corporation (MRC), MMM Group Ltd. (MMM) and WSP Canada Inc. (WSP). During this time, Doug held a variety of roles including Senior Project Manager and Senior Bridge Engineer, in addition to serving as Bridge Department Head in the Mississauga Office of MRC/MMM for more than 7 years.",
      "Doug is a member of the Technical Committee for the Canadian Highway Bridge Design Code (CHBDC) and a member of 3 subcommittees including Section 11 Joints and Bearings, and Section 15 Rehabilitation. Doug’s technical bridge engineering experience encompasses all aspects of engineering, including inspection, preliminary and detailed design, bridge rehabilitations, evaluations, bridge management and construction administration. Doug is respected in the industry by both Owners and Contractors.",
      "Doug is also a member of numerous professional organizations including a fellow of The Canadian Society for Civil Engineering.",
    ],
  },
  {
    fName: "Jigish",
    lName: "Naik",
    imgLink: "db/images/people/jnaik.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "M.Sc.",
    title: "Partner",
    group: "Leadership",
    content: [
      "Jigish Naik is a Partner and Senior Bridge Engineer at Doug Dixon & Associates with over 20 years of experience in the management, inspection, contract administration and design of bridges and culverts. Jigish is often called upon to share his bridge inspection expertise both within the bridge industry and at key industry events. Jigish has also conducted training sessions for parks staff of various municipalities including City of Toronto, City of Hamilton and Town of Milton. In addition, Jigish has trained numerous staff members for the OSIM inspections.",
      "Jigish is the Project Manager for the 6 Year Assignment for the City of Toronto to complete OSIM Bridge Inspections of more than 600 bridges in the City of Toronto for 3 complete biennial cycles.",
    ],
  },
  {
    fName: "Chris",
    lName: "Middleton",
    imgLink: "db/images/people/cmiddleton.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Senior Project Manager",
    group: "Professionals",
    content: [
      "Chris joined Doug Dixon & Associates Inc. (DDA) in 2019 and is a Senior Project Manager with more than 25 years of experience, including management, planning, design, rehabilitation and contract administration of bridges and culverts. Chris is a licensed Professional Engineer in the Province of Ontario.",
      "Chris experience includes specification and report writing, detailed condition surveys, visual inspections, resident site engineer, construction inspection, contract administration, construction material sampling, testing and inspection, rehabilitation design and detailing, structural design liaison and construction management. Chris experience includes projects with extensive coordination with municipalities, utilities, and sub-consultants, including geotechnical, hydrogeology (EASR/PTTW), fluvial geomorphology (MBW), cultural heritage and archaeological. Chris experience includes bridges (e.g., minor rehabilitations, deck replacements, superstructure replacements and full replacements) and culverts (e.g., re-lining and replacements) that involved migratory birds, and species at risk such as barn swallows.",
    ],
  },
  {
    fName: "Lolo",
    lName: "Tsung",
    imgLink: "db/images/people/ltsung.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Senior Project Manager",
    group: "Professionals",
    content: [
      "Lolo Tsung joined Doug Dixon and Associates Inc. (DDA) in 2022 as a Senior Project Manager and Senior Bridge Engineer within DDA. Lolo has more than twenty-five (25) years of experience in managing engineering professionals, project management, business administration, and construction administration. Lolo has worked on many highly complex and politically sensitive urban freeway projects on subways, highways, railways, and tunnels. Having hands-on experience working with concrete precast and construction companies, she excels at resolving complex design and construction issues with practical low-cost solutions. Her management experience includes project planning, risk-based cost and schedule assessments, value engineering studies, constructability reviews, schedule reviews, budget reviews, and client-contractor-stakeholder management. Her structural engineering experience includes structural inspections and preparation of preliminary and detailed designs in accordance with all municipal, provincial, and federal regulations and requirements. Project clients include the Ministry of Transportation of Ontario, the City of Toronto, the Toronto Transit Commission, Public Works and Government Services Canada, and various municipalities.",
    ],
  },
  {
    fName: "Charlotte",
    lName: "Bond",
    imgLink: "db/images/people/cbond.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Senior Bridge Engineer",
    group: "Professionals",
    content: [
      "Charlotte has over twelve (12) years of bridge engineering experience in the design, planning, analysis and evaluation of transportation structures. She has extensive experience in the design and evaluation of culverts and bridges of varying complexity. This includes steel plate girder bridges and precast concrete girder bridges of both single and continuous spans. Charlotte has been involved in multiple bridge rehabilitation designs and replacements, some of which involved innovative replacement strategies; such as, the use of SPMTs, launching devices, balanced cantilevers, and temporary cable stays and towers. Charlotte also has experience incorporating cathodic protection systems into rehabilitation designs to extend the life of existing structures. Additionally, she has experience designing replacement structures involving complex staging strategies, when necessary, when maintaining traffic is critical, as well as, when called for due to environmental constraints. Charlotte possesses extensive and demonstrated knowledge of the Canadian Highway Bridge Design Code, as well as, the Ministry’s policies, procedures, standards, specifications and manuals. Charlotte has successful comprehensive experience preparing contract document packages; including, contract drawings, specifications, special provisions, non-standard special provisions and applicable standard drawings. She has recent experience completing several MTO assignments involving preliminary and detailed design.",
      "Charlotte joined DDA in 2021 and has been involved in the detailed design of the Township of Centre Wellington Bridge 24-WG Replacement (23.1 m slab on precast girder bridge). She also completed the fatigue evaluation of the Eastern Avenue Bridge at the Don River Parkway for the City of Toronto, the inspection, evaluation and/or assessment of bridge rehabilitation alternatives (life cycle cost analysis) for the City of Toronto on the Metrolinx Railway Bridge over the Don Valley Parkway and the Dufferin Street Bridge over the Gardiner and Metrolinx Railway Corridor.",
    ],
  },
  {
    fName: "Jamie",
    lName: "Yeung",
    imgLink: "db/images/people/jyeung.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "PhD.",
    title: "Project Engineer",
    group: "Professionals",
    content: [
      "Jamie Yeung joined Doug Dixon and Associates Inc. (DDA) in May 2022 as an Intermediate Bridge Engineer. Jamie  graduated from the University of Waterloo with a Doctor of Philosophy in the field of Civil Engineering in 2011. His experience includes site inspection, contract administration, life cycle cost analysis, cost estimation, project scheduling, structural evaluation, preliminary design, and detailed design of both new and rehabilitation projects.",
      "Jamie is currently the Contract Administrator/Inspector for two (2) bridge rehabilitations and one (1) culvert replacement for the County of Brant. Jamie is also providing bridge construction liaison for the Bridge Street Bridge over Laurel Creek for the Region of Waterloo.",
    ],
  },
  {
    fName: "Sach",
    lName: "Jayasuriya",
    imgLink: "db/images/people/sjayasuriya.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Bridge Engineer",
    group: "Professionals",
    content: [
      "Sach joined Doug Dixon & Associates Inc. (DDA) as a Junior Bridge Engineer-in-Training in 2019. His experience includes structural rehabilitation using FRPs, finite element modelling (FEM), bridge inspection, and proposal writing.",
      "Sach holds a Master’s Degree in Civil Engineering from the University of Windsor, where he was involved in corrosion repair and strengthening of steel and RC beams, material testing, and structural testing and analysis of large-scale steel, concrete, and masonry specimens. Since joining DDA, he has been extensively involved in coordinating enhanced inspections with the City of Toronto and other appropriate parties and has gained a comprehensive understanding of performing OSIM inspections for various types of bridge structures. Sach has completed more than six hundred (600) bridge inspections for the City of Toronto’s Six (6) Year Assignment. In addition, he has completed detailed inspections of fire-damaged bridges, post-tensioned segmental bridges (Islington Ave. over Metrolinx Yard), four (4) temporary modular bridges for Dufferin Avenue over Metrolinx as well as completing the inspection and evaluation of the Overlea Boulevard Bridge over the Don River.",
    ],
  },
  {
    fName: "Kevin",
    lName: "Li",
    imgLink: "db/images/people/kli.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    altSuffix: "",
    title: "Bridge Engineer",
    group: "Professionals",
    content: [
      "Kevin has been with Doug Dixon & Associates Inc. (DDA) for over three (3) years. Kevin has completed independent reviews (3rd person reviews) of precast and steel girder bridge designs. Kevin has experience in obtaining utility and other clearances. Kevin joined DDA in June 2019 as a full-time Junior Bridge Designer after graduating from the University of Waterloo. Before graduating, Kevin completed internships at DDA, City of Toronto, and MTO’s Bridge Office. Kevin has over three (3) years of transportation infrastructure design, structural analysis/evaluation, field inspection, and construction administration experience. Kevin has performed and supervised over 200 OSIM and detailed bridge inspections, including deck condition surveys, fatigue inspections, and underwater inspections. Kevin is experienced with numerous structural design and analysis software programs including CsiBridge, Midas Civil, Advance Design America, SAP2000, and S-FRAME.",
      "Kevin participated in the detailed design, tendering preparation and construction inspection and administration for four (4) City of Toronto Culvert Replacements. Kevin has also completed the fatigue inspection for the Eastern Avenue Bridges at the Don Valley Parkway for the City of Toronto, the evaluation of the Dresden Bridge for Chatham-Kent and the Edinburgh multi-span rigid frames for the City of Guelph respectively and is currently preparing two (2) contracts to clean and coat more than 20,000 m² of steel bridges in the City of Toronto in 2023 and 2024.",
    ],
  },
  {
    fName: "Hayley",
    lName: "Kokkinakis",
    imgLink: "db/images/people/hkokkinakis.jpeg",
    refLink: "#team",
    suffix: "EIT",
    altSuffix: "",
    title: "Bridge Designer",
    group: "Designers",
    content: [
      "Hayley is a Junior Bridge Designer at Doug Dixon & Associates Inc. (DDA). Hayley has been with DDA for a total of sixteen (16) months. Hayley graduated in 2021 with a Bachelor’s degree in Civil Engineering with a Structural Specialization. Before graduating, Hayley completed multiple internships in bridge design, deep foundation design and trenchless technology. Hayley has experience with transportation structure design in the public sector as well as project coordination and administration. Additionally, Hayley has gained experience working with foundation design including the design of helical piles, micropiles and retaining walls. Hayley has experience with specialized software including but not limited to Midas Civil, SAP2000, and AutoCAD.",
      "Since joining DDA, Hayley has been involved in the preliminary design of the Greenock Creek Bridge/Hwy 9 Rehabilitation for MTO West Region; two (2) pedestrian bridges for the Town of Innisfil, the rehabilitation of two (2) rigid frame bridges (Morley Attleberry and Cauley) for the County of Brant and is currently working on the preliminary design of the County of Oxford’s Oxford Road 45 Bridge over the Thames River. She is also assisting the Project Manager on the underwater inspection of some twenty (20) bridges for the MTO Northwest Region.",
    ],
  },
  {
    fName: "Adam",
    lName: "Aubin",
    imgLink: "db/images/people/aaubin.jpeg",
    refLink: "#team",
    suffix: "EIT",
    altSuffix: "",
    title: "Bridge Designer",
    group: "Designers",
    content: [
      "Adam Aubin joined Doug Dixon and Associates Inc. in June of 2022 as a Junior Bridge Engineer-in-Training.",
      "Adam graduated in 2022 with a Bachelor’s degree in Civil engineering with a Structural specialization. Prior to graduation, Adam completed multiple internships in bridge design, and low-density residential and commercial renovation design.",
      "Adam has experience in the evaluation and design of bridge rehabilitations and OSIM inspections. Additionally, Adam participated in detailed design and contractor liason on low-density residential and commercial building renovations. Adam has experience with specialized software including but not limited to SAP2000 and AutoCAD.",
    ],
  },
  {
    fName: "Mahdi",
    lName: "Alfakisamani",
    imgLink: "db/images/people/unknown.jpg",
    refLink: "#team",
    suffix: "",
    altSuffix: "PhD.",
    title: "Junior Bridge Designer",
    group: "Designers",
    content: ["Loading...", ""],
  },
  {
    fName: "Evan",
    lName: "Tije",
    imgLink: "db/images/people/unknown.jpg",
    refLink: "#team",
    suffix: "",
    altSuffix: "",
    title: "Junior Bridge Designer",
    group: "Designers",
    content: ["Loading...", ""],
  },
];

export default teamLists;
