const teamLists = [
  {
    fName: "Doug",
    lName: "Dixon",
    imgLink: "db/images/people/ddixon.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    title: "President",
    group: "Leadership",
  },
  {
    fName: "Jigish",
    lName: "Naik",
    imgLink: "db/images/people/jnaik.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    title: "Partner",
    group: "Leadership",
  },
  {
    fName: "Chris",
    lName: "Middleton",
    imgLink: "db/images/people/cmiddleton.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    title: "Senior Project Manager",
    group: "Professionals",
  },
  {
    fName: "Lolo",
    lName: "Tsung",
    imgLink: "db/images/people/ltsung.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    title: "Senior Project Manager",
    group: "Professionals",
  },
  {
    fName: "Charlotte",
    lName: "Bond",
    imgLink: "db/images/people/cbond.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    title: "Senior Bridge Engineer",
    group: "Professionals",
  },
  {
    fName: "Jamie",
    lName: "Yeung",
    imgLink: "db/images/people/jyeung.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    title: "Project Engineer",
    group: "Professionals",
  },
  {
    fName: "Sach",
    lName: "Jayasuriya",
    imgLink: "db/images/people/sjayasuriya.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    title: "Bridge Engineer",
    group: "Professionals",
  },
  {
    fName: "Kevin",
    lName: "Li",
    imgLink: "db/images/people/kli.jpeg",
    refLink: "#team",
    suffix: "P.Eng.",
    title: "Bridge Engineer",
    group: "Professionals",
  },
  {
    fName: "Hayley", 
    lName: "Kokkinakis",
    imgLink: "db/images/people/hkokkinakis.jpeg",
    refLink: "#team",
    suffix: "EIT",
    title: "Engineer-in-Training",
    group: "Designers",
  },
  {
    fName: "Adam", 
    lName: "Aubin",
    imgLink: "db/images/people/aaubin.jpeg",
    refLink: "#team",
    suffix: "EIT",
    title: "Engineer-in-Training",
    group: "Designers",
  },
  {
    fName: "Mahdi", 
    lName: "Alfakisamani",
    imgLink: "db/images/people/unknown.jpg",
    refLink: "#team",
    suffix: "",
    title: "Engineer-in-Training",
    group: "Designers",
  },
  {
    fName: "Evan", 
    lName: "Tije",
    imgLink: "db/images/people/unknown.jpg",
    refLink: "#team",
    suffix: "",
    title: "Engineer-in-Training",
    group: "Designers",
  },
];

export default teamLists;
